// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYvmcqAowfSLbhAGQ5B-IEjG6VnJntSII',
    appId: '1:174082664505:web:1a4075283d3d5ff18445e8',
    messagingSenderId: '174082664505',
    projectId: 'cryptowallet-f79b1',
    authDomain: 'cryptowallet-f79b1.firebaseapp.com',
    storageBucket: 'cryptowallet-f79b1.appspot.com',
    measurementId: 'G-7W5PBZN1B8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5c0g5zUnZ4j9ztZcfGwAleoOSuVluipg',
    appId: '1:174082664505:android:ea5724b965ee4ff38445e8',
    messagingSenderId: '174082664505',
    projectId: 'cryptowallet-f79b1',
    storageBucket: 'cryptowallet-f79b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHkOvqwShaqsZU4gNz6rXQjv9nZ_4SoO4',
    appId: '1:174082664505:ios:99369b0a808e834b8445e8',
    messagingSenderId: '174082664505',
    projectId: 'cryptowallet-f79b1',
    storageBucket: 'cryptowallet-f79b1.appspot.com',
    iosClientId: '174082664505-54mg11jkslbpmssi2avu1pc5j772uru8.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptoWallet',
  );
}
